### GET ALL USER ATAU SEARCH BY USERNAME
GET http://localhost:3000/users/?search=

###
GET http://localhost:3000/users/uuid

### GET USER LOGIN
GET http://localhost:3000/currentusers

### UPDATE USER
PATCH  http://localhost:3000/users/d0e4e443-bc77-4919-8ab9-b2797ff8f2a1
Content-Type: application/json

{
  "username": "",
  "email": "",
  "password": "",
  "confPassword": "",
  "role": ""
}

### DELETE USER
DELETE   http://localhost:3000/users/9b4cb389-4cfc-4a50-91b5-cf3c1253d90a

### CREATE USER
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "",
  "email": "",
  "password": "",
  "confPassword": "",
  "file": "file image",
  "role": ""
}

### LOGIN
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "tes",
  "password": "1"
}

### LOGOUT
DELETE http://localhost:3000/logout

### GET PROPOSAL DAN SEARCH BY NAMA KEGIATAN
GET http://localhost:3000/proposal/?search=


### CREATE PROPOSAL
POST http://localhost:3000/proposal/dacaa7b7-bf42-4ce0-bc03-6a0a576afe63
Content-Type: application/json

{
  "nama_kegiatan": "festival gajah",
    "nama_organisasi": "ormawa",
    "jumlah_dana": "RP. 10.000.000",
    "ketua_panitia": "budi",
    "nomer_ketupat": "081731987321",
    "tanggal_pelaksanaan": "2022-12-12",
    "tempat_pelaksanaan": "lapangan",
    "nomer_ketum": "08129349283",
    "file": "file proposal",
    "status": "Proposal di ajukan"
}


### UPDATE PROPOSAL
PATCH http://localhost:3000/proposal/dacaa7b7-bf42-4ce0-bc03-6a0a576afe63
Content-Type: application/json

{
  "nama_kegiatan": "festival gajah",
    "nama_organisasi": "ormawa",
    "jumlah_dana": "RP. 10.000.000",
    "ketua_panitia": "budi",
    "nomer_ketupat": "081731987321",
    "tanggal_pelaksanaan": "2022-12-12",
    "tempat_pelaksanaan": "lapangan",
    "nomer_ketum": "08129349283",
    "file": null
}


### UPDATE STATUS PROPOSAL
PATCH http://localhost:3000/setstatus/7b70c6b1-8b2b-487f-af99-8c9a0a73da4c
Content-Type: application/json
{
  "status": "value"
}


### UPDATE KET WD3
PATCH http://localhost:3000/updateketeranganwd3/7b70c6b1-8b2b-487f-af99-8c9a0a73da4c
Content-Type: application/json
{
  "keteranganwd3": "value"
}

### UPDATE REVISI PROPOSAL
PATCH http://localhost:3000/updaterevisi/7b70c6b1-8b2b-487f-af99-8c9a0a73da4c
Content-Type: application/json
{
  "file": "file revisi proposal"
}

### UPDATE KET KEUANGAN DAN DANA DI ACC
PATCH http://localhost:3000/updatekeuangan/7b70c6b1-8b2b-487f-af99-8c9a0a73da4c
Content-Type: application/json
{
  "keterangankeuangan": "value",
  "dana_disetujui": "value"
}

### DELETE PROPOSAL
DELETE http://localhost:3000/proposal/93240fdd-0279-42ef-b82d-c699f65ddec2

### MULTIPLE DELETE
DELETE http://localhost:3000/proposal/
Content-Type: application/json

{
  "id": [3]
}


### UPLOAD SPJ
PATCH http://localhost:3000/spj/7b70c6b1-8b2b-487f-af99-8c9a0a73da4c
Content-Type: application/json

{
  "file": "file spj"
}

### UPLOAD BERKAS DUKUNG
PATCH http://localhost:3000/spj/berkasdukung/7b70c6b1-8b2b-487f-af99-8c9a0a73da4c
Content-Type: application/json

{
  "file": "file spj"
}

### UPLOAD LPJ
PATCH http://localhost:3000/lpj/7b70c6b1-8b2b-487f-af99-8c9a0a73da4c
Content-Type: application/json

{
  "file": "file spj"
}

### UPDATE KET AKADEMIK
PATCH http://localhost:3000/lpj/akademik/7b70c6b1-8b2b-487f-af99-8c9a0a73da4c
Content-Type: application/json

{
  "keterangan_akademik": "value"
}

### EXPORT TO EXCEL FILE
GET http://localhost:3000/export